config/routes.rb
WebGame2::Application.routes.draw do
  devise_for :users

  resources :cities
  
  match 'city/:id/travel' => 'cities#travel', :as => :travel_city
  
  resources :complexes
  
  resources :boxes
  
  match 'box/:id/open' => 'boxes#open', :as => :open_box
  match 'capsule' => 'boxes#buy', :as => :buy_box
  
  resources :fights
  
  match 'fight/:id/challenge' => 'fights#challenge', :as => :challenge_fight
  match 'fight/:id/defend' => 'fights#defend', :as => :defend_fight
  match 'fight/:id/dodge' => 'fights#dodge', :as => :dodge_fight
  match 'fight/:id/rest' => 'fights#rest', :as => :rest_fight
  match 'fight/:id/weapon_attack' => 'fights#weapon_attack', :as => :weapon_attack_fight
  match 'fight/:id/sidearm_attack' => 'fights#sidearm_attack', :as => :sidearm_attack_fight
  match 'fight/:id/parry' => 'fights#parry', :as => :parry_fight
  
  match 'fight/:id/result' => 'fights#result', :as => :result_fight
  
  resources :users, :module => :users
  
  resources :rooms
  
  match 'rooms/:id/guard' => 'rooms#guard', :as => :view_room_guard
  match 'guards/:id/assign' => 'rooms#change_guard', :as => :change_room_guard
  match 'guards/:id/unassign' => 'rooms#discard_guard', :as => :discard_room_guard
  match 'rooms/:id/pet' => 'rooms#pet', :as => :view_room_pet
  match 'pets/:id/assign' => 'rooms#change_pet', :as => :change_room_pet 
  match 'pets/:id/unassign' => 'rooms#discard_pet', :as => :discard_room_pet
  match 'rooms/:id/trap' => 'rooms#trap', :as => :view_room_trap
  match 'traps/:id/assign' => 'rooms#change_trap', :as => :change_room_trap 
  match 'traps/:id/unassign' => 'rooms#discard_trap', :as => :discard_room_trap
  
  match 'rooms/:id/furnishing' => 'rooms#furnishing', :as => :view_room_furnishing
  match 'furnishings/:id/assign' => 'rooms#add_furnishing', :as => :add_room_furnishing
  match 'furnishings/:id/unassign' => 'rooms#discard_furnishing', :as => :discard_room_furnishing
  
  match 'room/:id/buy' => 'rooms#buy', :as => :buy_room
  match 'room/:id/sell' => 'rooms#sell', :as => :sell_room
  
  resources :rings
  
  match 'rings/:id/buy' => 'rings#buy', :as => :buy_ring
  match 'rings/:id/equip' => 'rings#equip', :as => :equip_ring
  match 'rings/:id/unequip' => 'rings#unequip', :as => :unequip_ring
  match 'rings/:id/sell' => 'rings#sell', :as => :sell_ring
  
  resources :heads
  
  match 'heads/:id/buy' => 'heads#buy', :as => :buy_head
  match 'heads/:id/equip' => 'heads#equip', :as => :equip_head
  match 'heads/:id/unequip' => 'heads#unequip', :as => :unequip_head
  match 'heads/:id/sell' => 'heads#sell', :as => :sell_head
  
  resources :chests
  
  match 'chests/:id/buy' => 'chests#buy', :as => :buy_chest
  match 'chests/:id/equip' => 'chests#equip', :as => :equip_chest
  match 'chests/:id/unequip' => 'chests#unequip', :as => :unequip_chest
  match 'chests/:id/sell' => 'chests#sell', :as => :sell_chest
  
  resources :weapons
  
  match 'weapons/:id/buy' => 'weapons#buy', :as => :buy_weapon
  match 'weapons/:id/equip' => 'weapons#equip', :as => :equip_weapon
  match 'weapons/:id/unequip' => 'weapons#unequip', :as => :unequip_weapon
  match 'weapons/:id/sell' => 'weapons#sell', :as => :sell_weapon
  
  resources :sidearms
  
  match 'sidearms/:id/buy' => 'sidearms#buy', :as => :buy_sidearm
  match 'sidearms/:id/equip' => 'sidearms#equip', :as => :equip_sidearm
  match 'sidearms/:id/unequip' => 'sidearms#unequip', :as => :unequip_sidearm
  match 'sidearms/:id/sell' => 'sidearms#sell', :as => :sell_sidearm
  
  resources :legs
  
  match 'legs/:id/buy' => 'legs#buy', :as => :buy_leg
  match 'legs/:id/equip' => 'legs#equip', :as => :equip_leg
  match 'legs/:id/unequip' => 'legs#unequip', :as => :unequip_leg
  match 'legs/:id/sell' => 'legs#sell', :as => :sell_leg
  
  resources :boots
  
  match 'boots/:id/buy' => 'boots#buy', :as => :buy_boot
  match 'boots/:id/equip' => 'boots#equip', :as => :equip_boot
  match 'boots/:id/unequip' => 'boots#unequip', :as => :unequip_boot
  match 'boots/:id/sell' => 'boots#sell', :as => :sell_boot
  
  resources :hands
  
  match 'hands/:id/buy' => 'hands#buy', :as => :buy_hand
  match 'hands/:id/equip' => 'hands#equip', :as => :equip_hand
  match 'hands/:id/unequip' => 'hands#unequip', :as => :unequip_hand
  match 'hands/:id/sell' => 'hands#sell', :as => :sell_hand
  
  resources :guards
  
  match 'guards/:id/buy' => 'guards#buy', :as => :buy_guard
  match 'guards/:id/equip' => 'guards#equip', :as => :equip_guard
  match 'guards/:id/unequip' => 'guards#unequip', :as => :unequip_guard
  match 'guards/:id/sell' => 'guards#sell', :as => :sell_guard
  
  resources :traps
  
  match 'traps/:id/buy' => 'traps#buy', :as => :buy_trap
  match 'traps/:id/equip' => 'traps#equip', :as => :equip_trap
  match 'traps/:id/unequip' => 'traps#unequip', :as => :unequip_trap
  match 'traps/:id/sell' => 'traps#sell', :as => :sell_trap
  
  resources :pets
  
  match 'pets/:id/buy' => 'pets#buy', :as => :buy_pet
  match 'pets/:id/equip' => 'pets#equip', :as => :equip_pet
  match 'pets/:id/unequip' => 'pets#unequip', :as => :unequip_pet
  match 'pets/:id/sell' => 'pets#sell', :as => :sell_pet
  
  resources :furnishings
  
  match 'furnishings/:id/buy' => 'furnishings#buy', :as => :buy_furnishing
  match 'furnishings/:id/equip' => 'furnishings#equip', :as => :equip_furnishing
  match 'furnishings/:id/unequip' => 'furnishings#unequip', :as => :unequip_furnishing
  match 'furnishings/:id/sell' => 'furnishings#sell', :as => :sell_furnishing
  
  resources :list_guards
  resources :list_pets
  resources :list_traps
  resources :list_heads
  resources :list_hands
  resources :list_chests
  resources :list_rings
  resources :list_legs
  resources :list_boots
  resources :list_weapons
  resources :list_sidearms
  resources :colors
  
  
  root :to => 'users/users#show'
    
  

end

app/models/list_sidearm.rb
class ListSidearm < ActiveRecord::Base
  attr_accessible :description, :display_name, :min_block, :max_block, :level, :min_damage, :max_damage, :min_speed, :max_speed, :odds, :sidearm_image
  
  has_many :sidearms
  
  has_attached_file :sidearm_image,
    :styles => {
      :original => '120X250',
    }
    
  validates_attachment_size :sidearm_image, :less_than => 2.megabytes
end

app/controllers/list_sidearms_controller.rb
class ListSidearmsController < ApplicationController

  def new
    @list_sidearm = ListSidearm.new
  end
  
  def create
    @list_sidearm = ListSidearm.create(params[:list_sidearm])
    
    redirect_to list_sidearms_path
  end
  
  def edit
    @list_sidearm = ListSidearm.find(params[:id])
  end
  
  def update
    @list_sidearm = ListSidearm.find(params[:id])
    
    @list_sidearm.update_attributes(params[:list_sidearm])
    
    redirect_to list_sidearms_path
  end
  
  def index
    @list_sidearms = ListSidearm.all
  end
  
  def destroy
    @list_sidearm = ListSidearm.find(params[:id])
    
    @list_sidearm.destroy
    
    redirect_to list_sidearms_path
  end

end

app/helpers/list_sidearms_helper.rb
module ListSidearmsHelper
end

app/views/list_sidearms/edit.html.erb
<%= form_for @list_sidearm, :html => { :multipart => true } do |s| %>
  
    Display Name: <%= s.text_field :display_name, :placeholder => "Name that people will see..." %>
    Description: <%= s.text_area :description, :placeholder => "A paragraph about the sidearm..." %><br>
    Minimum Block Roll: <%= s.text_field :min_block, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Block Roll: <%= s.text_field :max_block, :placeholder => "Must be higher than min!" %><br>
    Minimum Damage Roll: <%= s.text_field :min_damage, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Damage Roll: <%= s.text_field :max_damage, :placeholder => "Must be higher than min!" %><br>
    Minimum Speed Roll: <%= s.text_field :min_speed, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Speed Roll: <%= s.text_field :max_speed, :placeholder => "Must be higher than min!" %><br>
    
    Odds: <%= s.text_field :odds, :placeholder => "1 - 1000000" %><br>
    
    Image: <%= s.file_field :sidearm_image %>
    
  <%= s.submit "Save Changes", :list_sidearm => @list_sidearm, :class => "btn btn-large btn-primary" %>

<% end %>

app/views/list_sidearms/index.html.erb
<%= link_to 'Create New sidearm', new_list_sidearm_path %><br><br>

<% if @list_sidearms != nil %>
<table width='900px'>
	<tr>
		<td>
			ID
		</td>
		<td>
			Display Name
		</td> 
		<td>
			Description
		</td> 
		<td>
			Min Speed
		</td> 
		<td>
			Max Speed
		</td> 
		<td>
			Min Damage
		</td> 
		<td>
			Max Damage
		</td> 
		<td>
			Min Block
		</td> 
		<td>
			Max Block
		</td> 
		<td>
			Odds
		</td> 
		<td>
			Image
		</td>
	</tr>
	

<% @list_sidearms.each do |s| %>

	<tr>
		
			
		
		<td>
			<%= s.id %>
		</td>
		<td>
			<%= s.display_name %>
		</td> 
		<td>
			<%= s.description %>
		</td> 
		<td>
			<%= s.min_speed %>
		</td> 
		<td>
			<%= s.max_speed %>
		</td> 
		<td>
			<%= s.min_damage %>
		</td> 
		<td>
			<%= s.max_damage %>
		</td> 
		<td>
			<%= s.min_block %>
		</td> 
		<td>
			<%= s.max_block %>
		</td> 
		<td>
			<%= s.odds %>
		</td> 
		<td>
			<%= image_tag s.sidearm_image %>
		</td>
	</tr>
	<tr>
		<td>
			<%= link_to 'Edit', edit_list_sidearm_path(s)%>
		</td>
		<td>
			<%= link_to 'Delete', list_sidearm_path(s), :method => :delete%>
		</td>
	</tr>
<% end %>
	</table>
<% else %>
 No sidearms Yet!
 <% end %>

app/views/list_sidearms/new.html.erb
<%= form_for @list_sidearm, :html => { :multipart => true } do |s| %>
  
    Display Name: <%= s.text_field :display_name, :placeholder => "Name that people will see..." %>
    Description: <%= s.text_area :description, :placeholder => "A paragraph about the sidearm..." %><br>
    Minimum Block Roll: <%= s.text_field :min_block, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Block Roll: <%= s.text_field :max_block, :placeholder => "Must be higher than min!" %><br>
    Minimum Damage Roll: <%= s.text_field :min_damage, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Damage Roll: <%= s.text_field :max_damage, :placeholder => "Must be higher than min!" %><br>
    Minimum Speed Roll: <%= s.text_field :min_speed, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Speed Roll: <%= s.text_field :max_speed, :placeholder => "Must be higher than min!" %><br>
    
    Odds: <%= s.text_field :odds, :placeholder => "1 - 1000000" %><br>
    
    Image: <%= s.file_field :sidearm_image %>
    
  <%= s.submit "Create sidearm", :list_sidearm => @list_sidearm, :class => "btn btn-large btn-primary" %>

<% end %>