config/routes.rb
WebGame2::Application.routes.draw do
  devise_for :users

  resources :cities
  
  match 'city/:id/travel' => 'cities#travel', :as => :travel_city
  
  resources :complexes
  
  resources :boxes
  
  match 'box/:id/open' => 'boxes#open', :as => :open_box
  match 'capsule' => 'boxes#buy', :as => :buy_box
  
  resources :fights
  
  match 'fight/:id/challenge' => 'fights#challenge', :as => :challenge_fight
  match 'fight/:id/defend' => 'fights#defend', :as => :defend_fight
  match 'fight/:id/dodge' => 'fights#dodge', :as => :dodge_fight
  match 'fight/:id/rest' => 'fights#rest', :as => :rest_fight
  match 'fight/:id/weapon_attack' => 'fights#weapon_attack', :as => :weapon_attack_fight
  match 'fight/:id/sidearm_attack' => 'fights#sidearm_attack', :as => :sidearm_attack_fight
  match 'fight/:id/parry' => 'fights#parry', :as => :parry_fight
  
  match 'fight/:id/result' => 'fights#result', :as => :result_fight
  
  resources :users, :module => :users
  
  resources :rooms
  
  match 'rooms/:id/guard' => 'rooms#guard', :as => :view_room_guard
  match 'guards/:id/assign' => 'rooms#change_guard', :as => :change_room_guard
  match 'guards/:id/unassign' => 'rooms#discard_guard', :as => :discard_room_guard
  match 'rooms/:id/pet' => 'rooms#pet', :as => :view_room_pet
  match 'pets/:id/assign' => 'rooms#change_pet', :as => :change_room_pet 
  match 'pets/:id/unassign' => 'rooms#discard_pet', :as => :discard_room_pet
  match 'rooms/:id/trap' => 'rooms#trap', :as => :view_room_trap
  match 'traps/:id/assign' => 'rooms#change_trap', :as => :change_room_trap 
  match 'traps/:id/unassign' => 'rooms#discard_trap', :as => :discard_room_trap
  
  match 'rooms/:id/furnishing' => 'rooms#furnishing', :as => :view_room_furnishing
  match 'furnishings/:id/assign' => 'rooms#add_furnishing', :as => :add_room_furnishing
  match 'furnishings/:id/unassign' => 'rooms#discard_furnishing', :as => :discard_room_furnishing
  
  match 'room/:id/buy' => 'rooms#buy', :as => :buy_room
  match 'room/:id/sell' => 'rooms#sell', :as => :sell_room
  
  resources :rings
  
  match 'rings/:id/buy' => 'rings#buy', :as => :buy_ring
  match 'rings/:id/equip' => 'rings#equip', :as => :equip_ring
  match 'rings/:id/unequip' => 'rings#unequip', :as => :unequip_ring
  match 'rings/:id/sell' => 'rings#sell', :as => :sell_ring
  
  resources :heads
  
  match 'heads/:id/buy' => 'heads#buy', :as => :buy_head
  match 'heads/:id/equip' => 'heads#equip', :as => :equip_head
  match 'heads/:id/unequip' => 'heads#unequip', :as => :unequip_head
  match 'heads/:id/sell' => 'heads#sell', :as => :sell_head
  
  resources :chests
  
  match 'chests/:id/buy' => 'chests#buy', :as => :buy_chest
  match 'chests/:id/equip' => 'chests#equip', :as => :equip_chest
  match 'chests/:id/unequip' => 'chests#unequip', :as => :unequip_chest
  match 'chests/:id/sell' => 'chests#sell', :as => :sell_chest
  
  resources :weapons
  
  match 'weapons/:id/buy' => 'weapons#buy', :as => :buy_weapon
  match 'weapons/:id/equip' => 'weapons#equip', :as => :equip_weapon
  match 'weapons/:id/unequip' => 'weapons#unequip', :as => :unequip_weapon
  match 'weapons/:id/sell' => 'weapons#sell', :as => :sell_weapon
  
  resources :sidearms
  
  match 'sidearms/:id/buy' => 'sidearms#buy', :as => :buy_sidearm
  match 'sidearms/:id/equip' => 'sidearms#equip', :as => :equip_sidearm
  match 'sidearms/:id/unequip' => 'sidearms#unequip', :as => :unequip_sidearm
  match 'sidearms/:id/sell' => 'sidearms#sell', :as => :sell_sidearm
  
  resources :legs
  
  match 'legs/:id/buy' => 'legs#buy', :as => :buy_leg
  match 'legs/:id/equip' => 'legs#equip', :as => :equip_leg
  match 'legs/:id/unequip' => 'legs#unequip', :as => :unequip_leg
  match 'legs/:id/sell' => 'legs#sell', :as => :sell_leg
  
  resources :boots
  
  match 'boots/:id/buy' => 'boots#buy', :as => :buy_boot
  match 'boots/:id/equip' => 'boots#equip', :as => :equip_boot
  match 'boots/:id/unequip' => 'boots#unequip', :as => :unequip_boot
  match 'boots/:id/sell' => 'boots#sell', :as => :sell_boot
  
  resources :hands
  
  match 'hands/:id/buy' => 'hands#buy', :as => :buy_hand
  match 'hands/:id/equip' => 'hands#equip', :as => :equip_hand
  match 'hands/:id/unequip' => 'hands#unequip', :as => :unequip_hand
  match 'hands/:id/sell' => 'hands#sell', :as => :sell_hand
  
  resources :guards
  
  match 'guards/:id/buy' => 'guards#buy', :as => :buy_guard
  match 'guards/:id/equip' => 'guards#equip', :as => :equip_guard
  match 'guards/:id/unequip' => 'guards#unequip', :as => :unequip_guard
  match 'guards/:id/sell' => 'guards#sell', :as => :sell_guard
  
  resources :traps
  
  match 'traps/:id/buy' => 'traps#buy', :as => :buy_trap
  match 'traps/:id/equip' => 'traps#equip', :as => :equip_trap
  match 'traps/:id/unequip' => 'traps#unequip', :as => :unequip_trap
  match 'traps/:id/sell' => 'traps#sell', :as => :sell_trap
  
  resources :pets
  
  match 'pets/:id/buy' => 'pets#buy', :as => :buy_pet
  match 'pets/:id/equip' => 'pets#equip', :as => :equip_pet
  match 'pets/:id/unequip' => 'pets#unequip', :as => :unequip_pet
  match 'pets/:id/sell' => 'pets#sell', :as => :sell_pet
  
  resources :furnishings
  
  match 'furnishings/:id/buy' => 'furnishings#buy', :as => :buy_furnishing
  match 'furnishings/:id/equip' => 'furnishings#equip', :as => :equip_furnishing
  match 'furnishings/:id/unequip' => 'furnishings#unequip', :as => :unequip_furnishing
  match 'furnishings/:id/sell' => 'furnishings#sell', :as => :sell_furnishing
  
  resources :list_guards
  resources :list_pets
  resources :list_traps
  resources :list_heads
  resources :list_hands
  resources :list_chests
  resources :list_rings
  resources :list_legs
  resources :list_boots
  resources :list_weapons
  resources :list_sidearms
  resources :colors
  
  
  root :to => 'users/users#show'
    
  

end

app/models/room.rb
class Room < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :complex
  belongs_to :pet
  belongs_to :guard
  belongs_to :trap
  
  has_many :furnishings
  has_many :fights  
  has_many :guards
  has_many :pets
  has_many :traps

  before_create :set_room_price
  
  def set_room_price
    self.buy = 5000
    self.sell = 5000
  end
  
  attr_accessible :fight, :display_name, :description, :image, :user, :complex, :worth, :buy, :sell, :guard, :pet, :trap
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
   before_filter :authenticate_user!
  
  def index   
    @rooms = Room.where('user_id LIKE ?', current_user.id).all
  end
  
  def buy
    @room = Room.find(params[:id])
    @user = current_user
    
    if @user.gold >= @room.buy and @room.user == nil
      
      if @room.guard != nil
        @room.guard.room = nil
        @room.guard = nil
      end
      if @room.pet != nil
        @room.pet.room = nil
        @room.pet = nil
      end
      if @room.trap != nil
        @room.trap.room = nil
        @room.trap = nil
      end
      
      @room.user = current_user
      @user.gold = @user.gold - @room.buy
      
      @room.save
      @user.save
      
      @rooms_left = Room.where('user_id IS NULL').all
      
      if @rooms_left.count < 15 
        Complex.create
      end
      
      redirect_to complex_path(@room.complex)
      
      
    else
      redirect_to complex_path(@room.complex)
      flash[:error] = 'You do not have enough gold to buy this room'
    end
  end
  
  def sell
    @room = Room.find(params[:id])
    @user = current_user
    
    if @user == @room.user
      
      if @room.guard != nil
        @room.guard.room = nil
        @room.guard = nil
      end
      if @room.pet != nil
        @room.pet.room = nil
        @room.pet = nil
      end
      if @room.trap != nil
        @room.trap.room = nil
        @room.trap = nil
      end
      
      
      
      @room.user = nil
      @user.gold = @user.gold + @room.sell
      
      Furnishing.where('room_id LIKE ?', @room.id).destroy_all
      
      @room.buy = 5000
      @room.sell = 5000
      
      @room.save
      @user.save
      
      redirect_to complex_path(@room.complex)
      flash[:success] = 'Congratulations on your sale!'
    else
      redirect_to complex_path(@room.complex)
      flash[:error] = 'You do not have enough gold to buy this room'
    end
  end
  
  def create
    
  end
  
  def guard
    @user = current_user
    @room = Room.find(params[:id])
    
    @guards = Guard.where('user_id LIKE ?', @user.id).all
  end
  
  def change_guard
    @user = current_user
    @guard = Guard.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @room.guard != nil or @guard.room != nil
      redirect_to view_room_guard_path(@room)
      
      flash[:error] = 'A room may only have one guard and a guard may only be assigned to one room.'
    else
    @guard.room = @room
    @room.guard = @guard
    
    
    @room.save
    @guard.save
    
    redirect_to view_room_guard_path(@room)
    end
  end
  
  def discard_guard
    @user = current_user
    @guard = Guard.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @guard.room == @room
      @guard.room = nil
      @room.guard = nil
      
      @room.save
      @guard.save
      
      redirect_to view_room_guard_path(@room)
    else
      redirect_to view_room_guard_path(@room)
      flash[:error] = 'Sorry, the request could not be completed'
    end
  end
  
  def pet
    @user = current_user
    @room = Room.find(params[:id])
    
    @pets = Pet.where('user_id LIKE ?', @user.id).all
  end
  
  def change_pet
    @user = current_user
    @pet = Pet.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @room.pet != nil or @pet.room != nil
      redirect_to view_room_pet_path(@room)
      
      flash[:error] = 'A room may only have one pet and a pet may only be assigned to one room.'
    else
    @pet.room = @room
    @room.pet = @pet
    
    
    @room.save
    @pet.save
    
    redirect_to view_room_pet_path(@room)
    end
  end
  
  def discard_pet
    @user = current_user
    @pet = Pet.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @pet.room == @room
      @pet.room = nil
      @room.pet = nil
      
      @room.save
      @pet.save
      
      redirect_to view_room_pet_path(@room)
    else
      redirect_to view_room_pet_path(@room)
      flash[:error] = 'Sorry, the request could not be completed'
    end
  end
  
  def trap
    @user = current_user
    @room = Room.find(params[:id])
    
    @traps = Trap.where('user_id LIKE ?', @user.id).all
  end
  
  def change_trap
    @user = current_user
    @trap = Trap.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @room.trap != nil or @trap.room != nil
      redirect_to view_room_trap_path(@room)
      
      flash[:error] = 'A room may only have one trap and a trap may only be assigned to one room.'
    else
    @trap.room = @room
    @room.trap = @trap
    
    
    @room.save
    @trap.save
    
    redirect_to view_room_trap_path(@room)
    end
  end
  
  def discard_trap
    @user = current_user
    @trap = Trap.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @trap.room == @room
      @trap.room = nil
      @room.trap = nil
      
      @room.save
      @trap.save
      
      redirect_to view_room_trap_path(@room)
    else
      redirect_to view_room_trap_path(@room)
      flash[:error] = 'Sorry, the request could not be completed'
    end
  end
  
  def furnishing
    @user = current_user
    @room = Room.find(params[:id])
    
    @furnishings = Furnishing.where('user_id LIKE ?', @user.id).all
  end
  
  def add_furnishing
    @user = current_user
    @furnishing = Furnishing.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    
    @furnishing.room = @room
    @room.buy = @room.buy + @furnishing.worth
    @room.sell = @room.sell + @furnishing.worth
    
    @room.save
    @furnishing.save
    
    redirect_to view_room_furnishing_path(@room)
    
  end
  
  def discard_furnishing
    @user = current_user
    @furnishing = Furnishing.find(params[:id])
    @room = Room.find(params[:room_to_equip])
    
    if @furnishing.room == @room
      @furnishing.room = nil
      
      @room.buy = @room.buy - @furnishing.worth
      @room.sell = @room.sell - @furnishing.worth
      
      @room.save
      @furnishing.save
      
      redirect_to view_room_furnishing_path(@room)
    else
      redirect_to view_room_furnishing_path(@room)
      flash[:error] = 'Sorry, the request could not be completed'
    end
  end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/furnishing.html.erb
<%= link_to 'Back to rooms', rooms_path %><br><br>



<% @furnishings.each do |f| %>

<% if f.room == nil%>
<%= f.display_name %>
<br>
<%= link_to 'Assign to this room', add_room_furnishing_path(f, :room_to_equip => @room) %>

<% else %>

<%= f.display_name %>
<br>
Currently setup in Room <%= f.room.id %>
<br>
<% if f.room == @room %>
<%= link_to 'Unassign furnishing', discard_room_furnishing_path(f, :room_to_equip => @room) %>
<% end %>

<% end %>

<br>
<br>
<% end %>

app/views/rooms/guard.html.erb
<%= link_to 'Back to rooms', rooms_path %><br><br>



<% @guards.each do |g| %>

<% if g.room == nil%>
<%= g.display_name %>
<br>
Health: <%= g.health %>
<br>
Damage: <%= g.min_damage %> - <%= g.max_damage %>
<br>
Speed: <%= g.min_speed %> - <%= g.max_speed %>
<br>
Block: <%= g.min_block %> - <%= g.max_block %>
<br>
<%= link_to 'Assign to this room', change_room_guard_path(g, :room_to_equip => @room) %>

<% else %>

<%= g.display_name %>
<br>
Health: <%= g.health %>
<br>
Damage: <%= g.min_damage %> - <%= g.max_damage %>
<br>
Speed: <%= g.min_speed %> - <%= g.max_speed %>
<br>
Block: <%= g.min_block %> - <%= g.max_block %>
<br>
Currently stationed in Room <%= g.room.id %>
<br>
<% if g.room == @room %>
<%= link_to 'Unassign Guard', discard_room_guard_path(g, :room_to_equip => @room) %>
<% end %>

<% end %>

<br>
<br>
<% end %>

app/views/rooms/index.html.erb
<%= link_to 'Back to inventory', root_path %><br>

<% @rooms.each do |r| %>
<Br>
Room Number <%= r.id %><br>
Complex: <%= r.complex.display_name %><br>
City: <%= r.complex.city.display_name %><br>

<% if r.guard == nil %>
No Guard Assigned<br>
<%= link_to 'Add a guard', view_room_guard_path(r) %>
<% else %>
Current Guard: <%= r.guard.display_name %><br>
<%= link_to 'Change guard', view_room_guard_path(r) %>
<% end %>
<br>
<% if r.pet == nil %>
No Pet Assigned<br>
<%= link_to 'Add a pet', view_room_pet_path(r) %>
<% else %>
Current Pet: <%= r.pet.display_name %><br>
<%= link_to 'Change pet', view_room_pet_path(r) %>
<% end %>
<br>
<% if r.trap == nil %>
No Trap Assigned<br>
<%= link_to 'Add a trap', view_room_trap_path(r) %>
<% else %>
Current Trap: <%= r.trap.display_name %><br>
<%= link_to 'Change trap', view_room_trap_path(r) %>
<% end %>
<br>


<%= link_to 'Add furnishings', view_room_furnishing_path(r) %>

<br>


<% end %>

app/views/rooms/new.html.erb
<h1>Create a New Room</h1><br>

<%= render 'form', :room => @room %>

</div>

app/views/rooms/pet.html.erb
<%= link_to 'Back to rooms', rooms_path %><br><br>



<% @pets.each do |p| %>

<% if p.room == nil%>
<%= p.display_name %>
<br>
Health: <%= p.health %>
<br>
Damage: <%= p.min_damage %> - <%= p.max_damage %>
<br>
Speed: <%= p.min_speed %> - <%= p.max_speed %>
<br>
Block: <%= p.min_block %> - <%= p.max_block %>
<br>
<%= link_to 'Assign to this room', change_room_pet_path(p, :room_to_equip => @room) %>

<% else %>

<%= p.display_name %>
<br>
Health: <%= p.health %>
<br>
Damage: <%= p.min_damage %> - <%= p.max_damage %>
<br>
Speed: <%= p.min_speed %> - <%= p.max_speed %>
<br>
Block: <%= p.min_block %> - <%= p.max_block %>
<br>
Currently stationed in Room <%= p.room.id %>
<br>
<% if p.room == @room %>
<%= link_to 'Unassign Pet', discard_room_pet_path(p, :room_to_equip => @room) %>
<% end %>

<% end %>

<br>
<br>
<% end %>

app/views/rooms/trap.html.erb
<%= link_to 'Back to rooms', rooms_path %><br><br>



<% @traps.each do |t| %>

<% if t.room == nil%>
<%= t.display_name %>
<br>
Health: <%= t.health %>
<br>
Damage: <%= t.min_damage %> - <%= t.max_damage %>
<br>
Speed: <%= t.min_speed %> - <%= t.max_speed %>
<br>
Block: <%= t.min_block %> - <%= t.max_block %>
<br>
<%= link_to 'Assign to this room', change_room_trap_path(t, :room_to_equip => @room) %>

<% else %>

<%= t.display_name %>
<br>
Health: <%= t.health %>
<br>
Damage: <%= t.min_damage %> - <%= t.max_damage %>
<br>
Speed: <%= t.min_speed %> - <%= t.max_speed %>
<br>
Block: <%= t.min_block %> - <%= t.max_block %>
<br>
Currently stationed in Room <%= t.room.id %>
<br>
<% if t.room == @room %>
<%= link_to 'Unassign Trap', discard_room_trap_path(t, :room_to_equip => @room) %>
<% end %>

<% end %>

<br>
<br>
<% end %>