config/routes.rb
WebGame2::Application.routes.draw do
  devise_for :users

  resources :cities
  
  match 'city/:id/travel' => 'cities#travel', :as => :travel_city
  
  resources :complexes
  
  resources :boxes
  
  match 'box/:id/open' => 'boxes#open', :as => :open_box
  match 'capsule' => 'boxes#buy', :as => :buy_box
  
  resources :fights
  
  match 'fight/:id/challenge' => 'fights#challenge', :as => :challenge_fight
  match 'fight/:id/defend' => 'fights#defend', :as => :defend_fight
  match 'fight/:id/dodge' => 'fights#dodge', :as => :dodge_fight
  match 'fight/:id/rest' => 'fights#rest', :as => :rest_fight
  match 'fight/:id/weapon_attack' => 'fights#weapon_attack', :as => :weapon_attack_fight
  match 'fight/:id/sidearm_attack' => 'fights#sidearm_attack', :as => :sidearm_attack_fight
  match 'fight/:id/parry' => 'fights#parry', :as => :parry_fight
  
  match 'fight/:id/result' => 'fights#result', :as => :result_fight
  
  resources :users, :module => :users
  
  resources :rooms
  
  match 'rooms/:id/guard' => 'rooms#guard', :as => :view_room_guard
  match 'guards/:id/assign' => 'rooms#change_guard', :as => :change_room_guard
  match 'guards/:id/unassign' => 'rooms#discard_guard', :as => :discard_room_guard
  match 'rooms/:id/pet' => 'rooms#pet', :as => :view_room_pet
  match 'pets/:id/assign' => 'rooms#change_pet', :as => :change_room_pet 
  match 'pets/:id/unassign' => 'rooms#discard_pet', :as => :discard_room_pet
  match 'rooms/:id/trap' => 'rooms#trap', :as => :view_room_trap
  match 'traps/:id/assign' => 'rooms#change_trap', :as => :change_room_trap 
  match 'traps/:id/unassign' => 'rooms#discard_trap', :as => :discard_room_trap
  
  match 'rooms/:id/furnishing' => 'rooms#furnishing', :as => :view_room_furnishing
  match 'furnishings/:id/assign' => 'rooms#add_furnishing', :as => :add_room_furnishing
  match 'furnishings/:id/unassign' => 'rooms#discard_furnishing', :as => :discard_room_furnishing
  
  match 'room/:id/buy' => 'rooms#buy', :as => :buy_room
  match 'room/:id/sell' => 'rooms#sell', :as => :sell_room
  
  resources :rings
  
  match 'rings/:id/buy' => 'rings#buy', :as => :buy_ring
  match 'rings/:id/equip' => 'rings#equip', :as => :equip_ring
  match 'rings/:id/unequip' => 'rings#unequip', :as => :unequip_ring
  match 'rings/:id/sell' => 'rings#sell', :as => :sell_ring
  
  resources :heads
  
  match 'heads/:id/buy' => 'heads#buy', :as => :buy_head
  match 'heads/:id/equip' => 'heads#equip', :as => :equip_head
  match 'heads/:id/unequip' => 'heads#unequip', :as => :unequip_head
  match 'heads/:id/sell' => 'heads#sell', :as => :sell_head
  
  resources :chests
  
  match 'chests/:id/buy' => 'chests#buy', :as => :buy_chest
  match 'chests/:id/equip' => 'chests#equip', :as => :equip_chest
  match 'chests/:id/unequip' => 'chests#unequip', :as => :unequip_chest
  match 'chests/:id/sell' => 'chests#sell', :as => :sell_chest
  
  resources :weapons
  
  match 'weapons/:id/buy' => 'weapons#buy', :as => :buy_weapon
  match 'weapons/:id/equip' => 'weapons#equip', :as => :equip_weapon
  match 'weapons/:id/unequip' => 'weapons#unequip', :as => :unequip_weapon
  match 'weapons/:id/sell' => 'weapons#sell', :as => :sell_weapon
  
  resources :sidearms
  
  match 'sidearms/:id/buy' => 'sidearms#buy', :as => :buy_sidearm
  match 'sidearms/:id/equip' => 'sidearms#equip', :as => :equip_sidearm
  match 'sidearms/:id/unequip' => 'sidearms#unequip', :as => :unequip_sidearm
  match 'sidearms/:id/sell' => 'sidearms#sell', :as => :sell_sidearm
  
  resources :legs
  
  match 'legs/:id/buy' => 'legs#buy', :as => :buy_leg
  match 'legs/:id/equip' => 'legs#equip', :as => :equip_leg
  match 'legs/:id/unequip' => 'legs#unequip', :as => :unequip_leg
  match 'legs/:id/sell' => 'legs#sell', :as => :sell_leg
  
  resources :boots
  
  match 'boots/:id/buy' => 'boots#buy', :as => :buy_boot
  match 'boots/:id/equip' => 'boots#equip', :as => :equip_boot
  match 'boots/:id/unequip' => 'boots#unequip', :as => :unequip_boot
  match 'boots/:id/sell' => 'boots#sell', :as => :sell_boot
  
  resources :hands
  
  match 'hands/:id/buy' => 'hands#buy', :as => :buy_hand
  match 'hands/:id/equip' => 'hands#equip', :as => :equip_hand
  match 'hands/:id/unequip' => 'hands#unequip', :as => :unequip_hand
  match 'hands/:id/sell' => 'hands#sell', :as => :sell_hand
  
  resources :guards
  
  match 'guards/:id/buy' => 'guards#buy', :as => :buy_guard
  match 'guards/:id/equip' => 'guards#equip', :as => :equip_guard
  match 'guards/:id/unequip' => 'guards#unequip', :as => :unequip_guard
  match 'guards/:id/sell' => 'guards#sell', :as => :sell_guard
  
  resources :traps
  
  match 'traps/:id/buy' => 'traps#buy', :as => :buy_trap
  match 'traps/:id/equip' => 'traps#equip', :as => :equip_trap
  match 'traps/:id/unequip' => 'traps#unequip', :as => :unequip_trap
  match 'traps/:id/sell' => 'traps#sell', :as => :sell_trap
  
  resources :pets
  
  match 'pets/:id/buy' => 'pets#buy', :as => :buy_pet
  match 'pets/:id/equip' => 'pets#equip', :as => :equip_pet
  match 'pets/:id/unequip' => 'pets#unequip', :as => :unequip_pet
  match 'pets/:id/sell' => 'pets#sell', :as => :sell_pet
  
  resources :furnishings
  
  match 'furnishings/:id/buy' => 'furnishings#buy', :as => :buy_furnishing
  match 'furnishings/:id/equip' => 'furnishings#equip', :as => :equip_furnishing
  match 'furnishings/:id/unequip' => 'furnishings#unequip', :as => :unequip_furnishing
  match 'furnishings/:id/sell' => 'furnishings#sell', :as => :sell_furnishing
  
  resources :list_guards
  resources :list_pets
  resources :list_traps
  resources :list_heads
  resources :list_hands
  resources :list_chests
  resources :list_rings
  resources :list_legs
  resources :list_boots
  resources :list_weapons
  resources :list_sidearms
  resources :colors
  
  
  root :to => 'users/users#show'
    
  

end

app/models/chest.rb
class Chest < ActiveRecord::Base
  belongs_to :user
  belongs_to :list_chest
  belongs_to :color
  
  before_create :randomly_make_chest
  
  def randomly_make_chest
    #everything is figured during initialization
    #You can call instance.make_weapon to do it at any time.
    
    #chance calculation for which one it picks from the list
    @odds = rand(1000000)
    
    @chest = ListChest.where('odds >= ?', @odds).order('RANDOM()').first
    
    self.list_chest = @chest
    
    self.display_name = @chest.display_name
    self.level = 1
    self.description = @chest.description
    
    self.base_min_speed = @chest.min_speed
    self.base_max_speed = @chest.max_speed
    self.base_min_block = @chest.min_block
    self.base_max_block = @chest.max_block
    
    self.min_speed = @chest.min_speed
    self.max_speed = @chest.max_speed
    self.min_block = @chest.min_block
    self.max_block = @chest.max_block
    
    #Chance Calculation for Quality
    random_quality = rand(1000)
    
    case random_quality
    when 0..500
      self.quality = 'Ugly'
    when 501..800
      self.quality = 'Stained'
      self.min_speed = self.min_speed * 0.98
    when 801..1000
      self.quality = 'Flexible'
      self.min_speed = self.min_speed * 1.23
      self.max_speed = self.max_speed * 1.12
    end
    
    #Chance to have a strength and weakness
    random_strength = rand(100)
    
    case random_strength
    when 0..89
      self.strength = nil
      self.weakness = nil
      self.strength_roll = nil
    when 90
      self.strength = 'Clean'
      self.weakness = 'Dirty'
      self.strength_roll = 2 + rand(3)
    when 91
      self.strength = 'Dirty'
      self.weakness = 'Well Groomed'
      self.strength_roll = 3 + rand(4)
    when 92
      self.strength = 'Well Groomed'
      self.weakness = 'Sloppy'
      self.strength_roll = 2 + rand(2)
    when 93
      self.strength = 'Sloppy'
      self.weakness = 'Diseased'
      self.strength_roll = 2 + rand(2)
    when 94
      self.strength = 'Diseased'
      self.weakness = 'Clean'
      self.strength_roll = 2 + rand(2)
    when 95
      self.strength = 'Enraged'
      self.weakness = 'Calm'
      self.strength_roll = 2 + rand(2)
    when 96
      self.strength = 'Calm'
      self.weakness = 'Chaotic'
      self.strength_roll = 2 + rand(2)
    when 97
      self.strength = 'Chaotic'
      self.weakness = 'Orderly'
      self.strength_roll = 2 + rand(2)
    when 98
      self.strength = 'Orderly'
      self.weakness = 'Rowdy'
      self.strength_roll = 2 + rand(2)
    when 99
      self.strength = 'Rowdy'
      self.weakness = 'Restrained'
      self.strength_roll = 2 + rand(2)
    when 100
      self.strength = 'Restrained'
      self.weakness = 'Enraged'
      self.strength_roll = 2 + rand(2)
    end 
    
    
    
    # Generate display name
    if self.strength == nil
      self.display_name = quality + ' ' + display_name
    else
    self.display_name = strength + ' ' + quality + ' ' + display_name
    end
    # Generate Buy and Sell Value
    self.buy = ((self.min_speed * 4) + (self.max_speed * 3)) + ((self.min_block * 5) + (self.max_block * 3))
    self.sell = (self.buy * 0.8).to_f
    
    
    
  end  
  
  attr_accessible :user, :active, :display_name, :description, :buy, :sell, :strength, :weakness, :strength_roll, :image, :min_speed, :max_speed, :min_block, :max_block
end

app/controllers/chests_controller.rb
class ChestsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def create
    @chest = Chest.create
    @chest.user = current_user
    
    @chest.save
    
    @user = current_user
    @user.stamina = @user.stamina - 1
    @user.save
    
    redirect_to chest_path(:id => @chest.id)
  end
  
  def show
    @chests = Chest.where('user_id LIKE ?', current_user.id ).where('bought IS NULL').all
  end
  
  def destroy
    @chest = Chest.find(params[:id])
    @chest.destroy
    Chest.where('user_id LIKE ?', current_user.id ).where('bought IS NULL').destroy_all
    
    redirect_to root_path
  end
  
  def buy
    @chest = Chest.find(params[:id])
    
    if current_user.gold >= @chest.buy
      current_user.gold = current_user.gold - @chest.buy
      @chest.user = current_user
      @chest.bought = true
      @chest.save
      current_user.save
      
      Chest.where('user_id LIKE ?', current_user.id ).where('bought IS NULL').destroy_all
      redirect_to root_path
    else
      redirect_to chest_path
      flash[:error] = 'You do not have enough gold to buy this'
    end
    
  end
  
  def index
    @user = current_user
    @chests = @user.chests
  end
  
  
  def equip
    Chest.where('user_id LIKE ?', current_user.id ).update_all( :active => nil )
    
    @chest = Chest.find(params[:id])
    @chest.active = true
    @chest.save
    
    redirect_to root_path
  end
  
  def unequip
    @chest = Chest.find(params[:id])
    @chest.active = nil
    @chest.save
    
    redirect_to chests_path
  end
  
  def sell
    @chest = Chest.find(params[:id])
    @user = current_user
    
    @user.gold = @user.gold + @chest.sell
    @user.save
    
    @chest.destroy
    
    redirect_to chests_path
  end
  
end

app/helpers/chests_helper.rb
module ChestsHelper
end

app/views/chests/edit.html.erb
<%= form_for @list_guard, :html => { :multipart => true } do |g| %>
  
    Display Name: <%= g.text_field :display_name, :placeholder => "Name that people will see..." %>
    Description: <%= g.text_area :description, :placeholder => "A paragraph about the guard..." %><br>
    Health: <%= g.text_field :health, :placeholder => "Health guard will start with." %><br>
    Minimum Block Roll: <%= g.text_field :min_block, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Block Roll: <%= g.text_field :max_block, :placeholder => "Must be higher than min!" %><br>
    Minimum Damage Roll: <%= g.text_field :min_damage, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Damage Roll: <%= g.text_field :max_damage, :placeholder => "Must be higher than min!" %><br>
    Minimum Speed Roll: <%= g.text_field :min_speed, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Speed Roll: <%= g.text_field :max_speed, :placeholder => "Must be higher than min!" %><br>
    
    Odds: <%= g.text_field :odds, :placeholder => "1 - 1000000" %><br>
    
    Image: <%= g.file_field :guard_image %>
    
  <%= g.submit "Save Changes", :list_guard => @list_guard, :class => "btn btn-large btn-primary" %>

<% end %>

app/views/chests/index.html.erb
<%= link_to 'Back to Inventory', root_path %><br><br>

<% @chests.each do |c| %>

<%= c.description %>
<br>
Speed Decrease: <%= c.min_speed %> - <%= c.max_speed %>
<br>
Block: <%= c.min_block %> - <%= c.max_block %>
<br>
Bought for: <%= c.buy %><br>
Resale Value: <%= c.sell%><br>
<%= link_to 'Equip', equip_chest_path(c) %>
<% if c.active == true %>
| <%= link_to 'Unequip', unequip_chest_path(c) %>
<% end %><br>
<%= link_to 'Sell', sell_chest_path(c) %>

<br>
<Br>
<% end %>

app/views/chests/new.html.erb
<%= form_for @list_guard, :html => { :multipart => true } do |g| %>
  
    Display Name: <%= g.text_field :display_name, :placeholder => "Name that people will see..." %>
    Description: <%= g.text_area :description, :placeholder => "A paragraph about the guard..." %><br>
    
    Health: <%= g.text_field :health, :placeholder => "Health guard will start with." %><br>
    Minimum Block Roll: <%= g.text_field :min_block, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Block Roll: <%= g.text_field :max_block, :placeholder => "Must be higher than min!" %><br>
    Minimum Damage Roll: <%= g.text_field :min_damage, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Damage Roll: <%= g.text_field :max_damage, :placeholder => "Must be higher than min!" %><br>
    Minimum Speed Roll: <%= g.text_field :min_speed, :placeholder => "ex.. 8, or 1 + rand(10)" %><br>
    Maximum Speed Roll: <%= g.text_field :max_speed, :placeholder => "Must be higher than min!" %><br>
    
    Odds: <%= g.text_field :odds, :placeholder => "1 - 1000000" %><br>
    
    Image: <%= g.file_field :guard_image %>
    
  <%= g.submit "Create Guard", :list_guard => @list_guard, :class => "btn btn-large btn-primary" %>

<% end %>

app/views/chests/show.html.erb
<% @chests.each do |c| %>
<%= c.display_name %>
<br>
Speed Decrease: <%= c.min_speed %> - <%= c.max_speed %>
<br>
Block: <%= c.min_block %> - <%= c.max_block %>
<br>
Cost: <%=c.buy %>
<br>
Resale Value: <%= c.sell %>
<br><br>

<% if current_user.gold >= c.buy %>
<%= link_to 'Buy', buy_chest_path(c) %> 
<% else %>
Buy
<% end %>

| <%= link_to 'No Thanks', chest_path(c), :method => :delete %>
<br><br>

<% end %>
<br>
<%= link_to 'Try Again', chests_path, :method => :post %>